name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: 3.4.3
  stacked_services: 1.5.0
  firebase_core: 3.1.1
  stacked_firebase_auth:
    path: ../

dev_dependencies:
  build_runner: 2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  mockito: 5.4.4
  stacked_generator: 1.6.0

dependency_overrides:
  stacked_firebase_auth:
    path: ../

flutter:
  uses-material-design: true

